deployphp/recipes

- README.md
- composer.json
- docs/slack.md
- recipes/slack.php
Added new recipe for sending messaging to Slack messaging system
> Slack notifications

- docs/rabbit.md
- recipes/rabbit.php
Added new config option to provide rabbitmq *vhost*.
> Added support for rabbitmq vhosts

- recipes/slack.php
> Refactored and added support for icon_url

- recipes/local.php
- recipes/rsync.php
In this PR:
- Fixed coding style of `local` and `rsync` recipe.
- Replace `echo` function on function check git version.
> Fixed coding style of local and rsync recipe

- docs/slack.md
- recipes/slack.php
the _license_ param does not exist (anymore!?), it should say _token_
> fix slack recipe doc

- README.md
- docs/hipchat.md
- recipes/hipchat.php
> Hipchat recipe

- docs/hipchat.md
- recipes/hipchat.php
As mentiod by @ZhukV, if you run your own hipchat server, the endpoint has to be configurable.
> Make hipchat API endpoint configurable

- docs/cachetool.md
- recipes/cachetool.php
> Added possibility to specify cachetool options per server (using env)

- recipes/cachetool.php
- recipes/local.php
| Fixed tickets | https://github.com/deployphp/deployer/pull/608
Fix for custom bin feature, refs https://github.com/deployphp/deployer/pull/608
> Fix for custom bin feature

- recipes/slack.php
If the slack config is missing essential parts, there's no point going any further.
> Exit early on incomplete Slack config

- docs/local.md
- recipes/local.php
> Fixed using bin paths in local recipe

- README.md
- docs/cloudflare.md
- recipes/cloudflare.php
Howdy doody,
We attach a cloudflare cache clearing recipie for your delight and delication.
Cheers
Cyber Duck
> Cloudflare cache clearing recipe

- recipes/rsync.php
> Fix Rsync when used locally

- docs/rollbar.md
- recipes/rollbar.php
[Rollbar](https://rollbar.com/) notifications
> Add rollbar recipe

- README.md
- docs/phinx.md
- phinx.php
- recipes/phinx.php
Another PR to merge(because of a problem to merge previous PR). See #54.
> Phinx recipe

- slack.php
This is an update of #60 .
What do you think @elfet ?
> Improve Slack integration

- docs/phinx.md
- phinx.php
Fix with functions in 'set'
Add deployer namespace
Change docs according to v4 changes
> Issue #74 fixes

- rsync.php
Fix getPrivateKey Change to getPemFile to work with deployer 4.
> Fix getPrivateKey Change to getPemFile to work with deployer 4.

- composer.json
This should be done together with abandoning deployphp/recipes on Packagist.
> Add replace for "deployphp/recipes"

- docs/npm.md
Also mention "local/bin/npm" configuration option.
> Document "npm:local:install" task

- configure.php
- docs/configure.md
Add deploy:configure command for make configure files for stage from templates like version 3.x
:smile:
> Add deploy:configure command for make configure files for stage from templates

- configure.php
Fix follow @mbrodala 's review in PR #102 
- Changed `$paser` to `$parser`
- Show error on fail. Now it look like:
```
➤ Executing task deploy:configure
✘ test.tpl
ERROR: Configuration parameter `a` does not exists.
✔ Ok
```
> Fix follow @mbrodala 's review

- slack.php
> take branch option if set

- docs/phinx.md
Realized the documentation was a bit out of date and figured it out
with a bit of research on my own.
> Update to Phinx recipe documentation

- cloudflare.php
This pull request fixes a few possible bugs with the Cloudflare recipe.
**The changelog is a follows:**
- fixed a possible class/exception not found error
- fixed a possible uninitialized variable
> Minor fixes for the Cloudflare recipe

- docs/rsync.md
- recipe/rsync.php
| Deprecations? | Yes
| Fixed tickets | [#126](https://github.com/deployphp/recipes/issues/126)
Improved the rsync recipe to work with Deployer version 5.
> Modifications for Deployer 5

- recipe/rsync.php
Fixed local deployment with Deployer 5, because I forgot this in the previous [PR](https://github.com/deployphp/recipes/pull/129).
> Fixed local deployment with Deployer 5

- recipe/rollbar.php
- Fix: Call stage var instead of stages array
- Fix: Use Host object instead of Server
> Fix Rollbar recipe

- recipe/phinx.php
> fixed catch block for deployer version 5

- docs/sentry.md
- sentry.php
| Bug fix?      |  No
Add the ability to set a custom sentry server.
> Add sentry Custom server - 4.x

- recipe/rsync.php
Resolves issue described in https://github.com/deployphp/deployer/issues/1284
| Fixed tickets | https://github.com/deployphp/deployer/issues/1284
> Update rsync recipe to use real hostname

- docs/rsync.md
> fix small typo

- recipe/slack.php
- Fix: Replace empty stage by actual stage
- Improvement: Parse config channel with messagePlaceHolders to give more flexibility
- Cleanup: Remove var_dump
- Cleanup: Remove hardcoded user Aton
> Fix and clean Slack recipe

- CHANGELOG.md
- docs/hipchat.md
- recipe/hipchat.php
Allow setting the URL if you are using a self hosted hipchat instance
> Allow changing the server URL

- CHANGELOG.md
- recipe/telegram.php
> Telegram recipe

- docs/hipchat.md
> Update hipchat task name to hipchat:notify

- CHANGELOG.md
- recipe/telegram.php
> Fix bug with message formatting in telegram notifications.

- CHANGELOG.md
- docs/slack.md
- recipe/slack.php
> Add slack:notify:failure task

- CHANGELOG.md
- README.md
- docs/raygun.md
- recipe/raygun.php
- Adds Raygun recipe and documentation.
> Raygun Deployment Recipe

- CHANGELOG.md
- recipe/rsync.php
ssh command on rsync.php execute only identityFile option.
so, modify to make ssh command line options from Ssh module on deployer base system.
> replace code to make ssh arguments.

- CHANGELOG.md
- docs/grafana.md
- recipe/grafana.php
- Adds Grafana recipe and documentation.
> Add grafana recipe and documentation

- docs/newrelic.md
I was having difficulty with my deployer config until i noticed that the task named in this part of the config was incorrect.
> Fix example in newrelic documentation

- CHANGELOG.md
- recipe/newrelic.php
Error response from NewRelic on current version: 
```
{"error":{"title":"missing parameter: deployment"}}
````
> changed body to query function

- CHANGELOG.md
- docs/chat.md
- recipe/chat.php
> Google hangouts chat

- CHANGELOG.md
- docs/sentry.md
- recipe/sentry.php
API URL and params changed:
https://docs.sentry.io/api/releases/post-organization-releases/
> fixed sentry notification recipe to work with latest API changes

- docs/telegram.md
- recipe/telegram.php
> Added ability to send Telegram notifies through a proxy

- .gitignore
- CHANGELOG.md
- composer.json
- docs/sentry.md
- recipe/sentry.php
added .gitignore
added composer dev dependency for deployer/deployer main repo as discussed in #126
added support for sending commits to sentry
added deployment creation after release creation for sentry
> improved sentry notifications and added composer dev dependency

- configure.php
> Update compiler pattern to support same as Deployer 6

- CHANGELOG.md
- README.md
- docs/cimonitor.md
- recipe/cimonitor.php
| Bug fix?      | NO
This PR adds a recipe for CIMonitor (https://github.com/CIMonitor/CIMonitor).
> CIMonitor recipe

- docs/sentry.md
- recipe/sentry.php
In our case we would like to describe the versions differently so i've added the option to overwrite the git command. Also i've added an example of another command to the docs. 
| Fixed tickets | N/A or xx
> [Sentry] Added overwrite config for the git command

- docs/telegram.md
- recipe/telegram.php
| Bug fix?      |  No
| Fixed tickets | 174
> Telegram failed notify

- docs/bugsnag.md
Fix incorrect bugsnag deployment command in documenation
| Fixed tickets | No
> Incorrect documentation

- CHANGELOG.md
- docs/cachetool.md
- recipe/cachetool.php
> Add APCu support in cachetool recipe

- recipe/sentry.php
***
@antonmedv @petermein @Gamesh
I've encountered an error:  
`fatal: Invalid revision range <hash>..HEAD`  
which prevented the deploy process from finishing. So I had to wrap the git command in try...catch. Probably not the best way to go about that, but I had to do it locally to deploy my project.
> use try...catch

- composer.json
- recipe/sentry.php
| Fixed tickets | #210 
fixes usage of 7.1 syntax to deconstruct array
> fixes issue #210

- recipe/rsync.php
> fix rsync filterPerDir variable

- docs/rocketchat.md
- recipe/rocketchat.php
> Add rocketchat integration

- README.md
- docs/ms-teams.md
- recipe/ms-teams.php
| BC breaks?    | Yes or No
| Fixed tickets | #229
PR for #229 MS Teams notification integration.
> PR for #229 MS Teams notification integration 

- docs/bugsnag.md
> Update reference to task in usage

- recipe/cachetool.php
> More control and customization for cachetool recipe

- CHANGELOG.md
- recipe/npm.php
> If package.json is unmodified, then skip running `npm install`

- CHANGELOG.md
- docs/workplace.md
- recipe/workplace.php
> Add Workplace recipe

- recipe/sentry.php
> Fix #228 code

- README.md
- docs/mattermost.md
- recipe/mattermost.php
> Add mattermost integration

- recipe/sentry.php
| Bug fix?      |  No
| BC breaks?    |  No
| Deprecations? |  No
> Add message in sentry release

- recipe/phinx.php
| Fixed tickets | #83 
The problem was pretty well discussed, but as I understand, a PR was never made and the recipe still fails even with this simple setup:
```php
task('deploy', [
'phinx:breakpoint',
'phinx:migrate',
]);
```
> Fix the Phinx recipe
