README.md
composer.json
docs/rabbit.md
recipes/rabbit.php

I need notify rabbitmq on one project after deployment so i created recipe. I need one dependency for this - [videlalvaro/php-amqplib](https://github.com/videlalvaro/php-amqplib) than I am not sure if it is ok. If you would like to keep this library without external dependencies, than reject this pull request.

Added support for notifying rabbmiq server

---

README.md
docs/rsync.md
recipes/rsync.php

```php
// deploy.php
require 'vendor/deployphp/recipes/recipes/rsync.php';
```
- **rsync_excludes** *(optional)*: accepts a *array* with files/dirs to be excluded from sending to server
- **rsync_user** *(optional)*: accepts a *string* with username to server
- **rsync_local_release_dir** *(optional)*: accepts a *string* with dirname where temporary repository cloning should take place before being sent to server
```php
// deploy.php
set('rsync_excludes', [
'.git',
'deployer_release',
'releases',
'deploy.php',
]);
set('rsync_user', 'server_user');
set('rsync_local_release_dir', '/tmp');
```
- `deploy:local_release` Creates local release directory
- `deploy:update_code` overrides standard `deploy:update_code` to update code locally instead of remotelly
- `deploy:rsync` perorms rsync from …

Adds a Rsync recipe, basis for performing repository-related tasks locally

---

README.md

Rather than leave it to #11, it's better to have guidelines in [README](README.md) file. 
Additionally this pr addds missing `rsync` recipe, but that could be obsoleted by #16 ;)

Readme addons - add guidelines for new recipes

---

recipes/rsync.php

I run into bit of trouble with rsync when depending on server, rsync is weirdly different. Consider this code:
```php
server('production', 'prod.server', 22)
->user('Product')
->stage('production')
->forwardAgent()
->env('deploy_path', '/var/www/vhosts/product')
->env('rsync_src', function() {
$local_src = env('local_release_path');
if (is_callable($local_src)) {
$local_src = $local_src();
}
return $local_src;
});
server('dev', 'devel.preview', 22)
->user('preview')
->stage('dev')
->forwardAgent()
->env('deploy_path', '/var/www/vhosts/preview.host/product')
->env('rsync_src', __DIR__)
->env('rsync_dest', '{{current}}');
```
Using rsync without this PR, I got error:
> PHP Catchable fatal error:  Object of class Closure could not be converted to string
on rsync task for production (but not …

Fix rsync behaviour with callable environment vars

---

recipes/rsync.php

This simply adds "/" to end of src. I don't know how I could omit it... I swear it was there! If You tried to use it it would not work otherwise, it would send scr dir as a subdir to dst dir, which is not something most would want.

Fix rsync scr not ending in '/'

---

recipes/local.php

I've seen changes @oanhnn made. I was intigued by output being written and I've noticed that echo wound up there unnecessary. Output isn't present in git_cache in common.php that was based on this, so I guess I forgot to make change @elfet requested there present here too.

Remove completelly unneded outputing of git version

---

recipes/configure.php

In this PR:
* fix issue relative path when uploading with ext-ssh2, refs https://github.com/deployphp/deployer/issues/387
* fix don't ignore dot file (Eg: `.env.tpl` in laravel 5)

fix issue relative path when uploading with ext-ssh2

---

docs/rsync.md
recipes/rsync.php

When syncing large repo, or when syncing using crappy net connection, it could be *very* frustrating to run rsync after rsync just to sync everything. Instead, allow user to define timeout and use it in `runLocally` call.

Add timeout optionfor rsync run

---

docs/slack.md
recipes/slack.php

I wanted to customize the message sent to slack, but found it hard to find the available variables. Also it wasn't clear to me how to add the name of the user deploying... so here is my proposal (more place holders should/could be added - like the tag name when available for instance - but those serve my needs for now).

add support for place holders in slack messages

---

recipes/rsync.php

if $dst is not set here we are going to sync to root and even worse - depending on rsync flags and permission - might end up deleting everything we have write permission to

prevent rsync without $dst set

---

recipes/rsync.php

Even when set, the rsync command doesn't use the identityFile given from server configuration. Instead it will ask for password of the user.
Changed to use the identityFile. Passphrase would be asked anyway, as sshpass or any other similar program may not be available on the system. To use it the 'easy' way, creating a keyfile w/o passphrase would be a way, but security risk too.

rsync recipe doesn't use identityFile

---

docs/slack.md

The link had a typo and was out-dated.
Not anymore!

Fixed the link to the Slack Api Token page

---

rsync.php

With new release management (in deployer 4.0), `rsync:warmup` do not work anymore.
This PR fix #77. 
It use `current` and `release` symlinks to copy previous release code in new release directory.

Fix rsync:warmup task

---

phinx.php

Binaries within Deployer are usually referred to via "{{bin/foo}}" thus rename the
variable accordingly.
Backward compatibility is kept for now by using the old variable name if not empty.

Apply convention to Phinx binary variable

---

npm.php

The `npm` recipe supports running `npm install` on a server. When using the `local` recipe it would be nice to be able to run `npm install` locally and then deploy the result.
This PR adds a new task to the `npm` recipe which does that: `npm:install_local`.
A couple of comments:
- The current implementation is quite naive. Suggestions on how to improve it are appreciated.
- This is in essence an integration between two recipes. I do not know in which the result should live. I opted for the `npm` recipe for now.
- If you like the PR I will update the documentation.

Run npm install locally

---

newrelic.php

This allows users to set them during deployment. Current defaults are 
kept intact.

Use params for New Relic deployment data

---

local.php

Without this change `local:update_code` does not respect the branch and revision input options.
This brings the task up to par with `deploy:update_code`.

Allow override of branch, tag and revision from input on local:update_code

---

docs/newrelic.md
newrelic.php

[V1 has been deprecated](https://docs.newrelic.com/docs/apis/rest-api-v1-deprecated/new-relic-rest-api-v1/working-new-relic-rest-api-v1-deprecated#deploy). This means we now post JSON encoded data to a 
new endpoint.
Warn existing users that configuration values `app_name` and `license` have 
been replaced by `application_id` and `api_key`.
See https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/recording-deployments

Use New Relic Deployment API V2

---

slack.php

this gives fatal error with v4.0.2
```                                                                 
[RuntimeException]                                                 
env() function deprecated. Please, use set() or get() instead of.  
```

slack: do not use deprecated env()

---

rsync.php

The default timeout for local commands [was raised to 300 seconds](https://github.com/deployphp/deployer/commit/9680b11cc4fad7d83abb79ad16eb4ea9fd2ba0c2), thus do not lower this by default.

Raise default rsync timeout

---

docs/newrelic.md

This is necessary because the newrelic.php script checks the license array.

Changed the parameter api_key to license

---

rsync.php

Added checks for both .pem and private key files to provide compatibility for people using privateKey files instead of pem files.

rsync: Compatibility for both key and pem authentication

---

slack.php

and some formatting. 
There are 2 more things which I would like to change, but wasn't sure about. 
The first thing is the ```global $php_errormsg```. Is it possible to delete that line and just remove the @ at the ```file_get_content``` or wouldn't it work anymore afterwards?
The second thing is, that I wanted to get rid of some local variables and outsource them to their own set calls, like ```local_user ```. Namely I thought about the `$user`, `$revision`, `$stage` and `$branch` variables.

"Make unsets if other fieldParams are set" logic more compact

---

configure.php

fixes the problem that
`__DIR__` returns `/path/to/project/vendor/deployer/recipes`
and not as expected `/path/to/project/`
For additional informations see #112

fix for deployphp/recipes#112

---

rsync.php

Since this can generate a lot of output which cannot be prevented
if one wants to see command output at the same time, this is reverted
again. If required, one can simply configure rsync flags manually.
This reverts commit 1d87a76e7f3438c3455d53a2a389be59738c7fff.

Revert "Make rsync verbose on -vvv"

---

slack.php

Due to a recent commit support for PHP 5.x broke. This commit reverts the change for Slack.

Fix PHP 7 only coalesce syntax

---

docs/phinx.md
phinx.php

Also, update corresponding documentation.
Just thought it'd be helpful to add another method to the phinx recipe, as I need the ability to set a breakpoint before I run the latest migrations as a precaution, so I may roll back any incomplete migrations.

Add breakpoint command to Phinx recipe

---

README.md
docs/yarn.md
yarn.php

*Adding Yarn support, inspired by the NPM recipe.*
```php
// deploy.php
require 'vendor/deployer/recipes/yarn.php';
```
- **bin/yarn** *(optional)*: set Yarn binary, automatically detected otherwise.
- **local/bin/yarn** *(optional)*: set local Yarn binary, automatically detected otherwise. 
By default, if no env setting is provided, this recipe will fallback to the global setting.
- `yarn:install` Install Yarn packages
- `yarn:local:install` Install Yarn packages into a locally prepared release. This should be used with the [local recipe](docs/local.md).
```php
after('deploy:update_code', 'yarn:install');
// or
before('deploy:symlink', 'yarn:install');
// or local
after('local:update_code', 'yarn:local:install');
```

Yarn recipe added

---

recipe/rsync.php

The code was not setting actual identityFile path and only the identityMethod. This was causing the rsync failure. Here's the error. there is nothing after -i
[Symfony\Component\Process\Exception\ProcessFailedException]
The command "rsync -rz -e 'ssh -p22 -i ' --delete --exclude='.git' --exclude='deploy.php' --exclude='node_modules' '/tmp/deployer/releases/20170417145717/' 'someuser@IPADDRESS:/home/ec2-user/staging/releases/4/'" failed.

Not getting actual pem file path in rsync

---

recipe/rsync.php

I realized during the review of the new PRs that the naming changed too, so I improved it in the rsync recipe.

rsync: Fixed naming for local deployments

---

docs/sentry.md
recipe/sentry.php

| Bug fix?      |  No
Add the ability to set a custom sentry server.

Add sentry Custom server - 5.x

---

docs/rollbar.md

This change fixes usage instructions in the documentation as `deploy:rollbar` task doesn't exist and `rollbar:notify` is the actual task that should be used.

Fix incorrect task name

---

slack.php

1. Fix prev commit "make unsets when other fieldParams are set logic more compact" - impossible to disable unset of `text` param. To turn ON unset of `text` just add `unset_text: true` to config.
2. Real hostname in **Host** attachment block.
3. Add customization of attachment color & title by adding to slack config `attachmentCustom`:
```
slack:
token: xoxp...
...
attachmentCustom:
color: '#a94442'
```

Slack interg improve

---

docs/slack.md

Replaced `after('deploy:failure', 'slack:notify:failure');` with `after('deploy:failed', 'slack:notify:failure');`

Updated the docs of the Slack recipe.

---

CHANGELOG.md
README.md
docs/yammer.md
recipe/yammer.php

I have created Microsoft Yammer's integration. This recipe is based on Slack recipe.
Supported tasks.
- `yammer:notify` – send message to Yammer
- `yammer:notify:success` – send success message to Yammer
- `yammer:notify:failure` – send failure message to Yammer
In Yammer is looks like below.

Add yammer recipe and documentation

---

CHANGELOG.md
README.md
docs/telegram.md
recipe/telegram.php

| Fixed tickets | #170 
Thanks for deployer, it saves me lots of time!
Fixed telegram recipe, that used undefined variables (probably left from demo). Also added `telegram_chat_id` parameter to docs.
If one of  `telegram_token` or `telegram_chat_id` is unset, the `\Exception` is thrown (based on other recipes).
Last thing is that I added link to telegram recipe doc to README.

Fix telegram recipe and docs

---

docs/slack.md

I added a note + temporary workaround for https://github.com/deployphp/deployer/issues/1371 so that users don't have to waste time figuring out why this isn't working currently. This will be reverted hopefully once v7 is released with a fix.
I also added better examples to the configurations so that new users would know exactly how to use the commands.

Added note about current bug with autoload

---

docs/slack.md

I know the require path was replaced in the doc as a temp fix, but I imagine it'd be better to give the proper path anyway :)

Typo in slack recipe (temp) path

---

CHANGELOG.md
docs/discord.md
recipe/discord.php

| Fixed tickets | #181 
This pr fixes ticket #181
------
I also tried to make it possible to set `discord_message` directly.
```php
// Helpers
task('discord_send_message', function(){
$message = get('discord_message');
if(has($message)){
$message = get($message);
}
Httpie::post(get('discord_webhook'))->body(['text' => $message])->send();
});
```
But I can't check it with `has`, it always returns `false`. After debugging I also saw that the context configuration only contains the host information and the key `discord_message`, the others are stored in the `Deployer` instance configuration. I'm ready to provide a pr if I get any solution.

Fix for discord recipe

---

CHANGELOG.md
README.md
recipe/discord.php

--------------
Hey @chapterjason thanks a lot for your previous fix, but it ended up to unable user to send 'complex' messages, just like this:
```php
set('discord_notify_text', function () {
return [
'attachments' => [
[
'title' => get('application') . ' Application Has Started Deploying...',
'fields' => [
[
'title' => 'Environment',
'value' => get('stage'),
'short' => true
],
[
'title' => 'Branch',
'value' => get('branch') ?: 'master',
'short' => true
],
[
'title' => 'Deployer',
'value' => get('user'),
'short' => …
```

Allow messages to be complex on Discord recipe

---

CHANGELOG.md
recipe/newrelic.php

This allows you to override revision retrieval for custom builds. This
is useful for builds where the revision is not in the current
directory.

Use configuration for New Relic revision

---

CHANGELOG.md
recipe/newrelic.php

This allows setting the app ID to false when deploying to environments not monitored by New Relic. You'll still receive an error message if you don't manually override `newrelic_app_id`.
| Fixed tickets | #193

Notify New Relic only if app ID and key are set

---

recipe/sentry.php

Sentry requires the content-type headers to accept certain api requests. I've added these headers to both requests.
Already covert in the previous recipe message

[Sentry] Added content type headers to sentry requests

---

docs/cpanel.md
recipe/cpanel.php

This is a recipe that uses the [cPanel 2 API](https://documentation.cPanel.net/display/DD/Guide+to+cPanel+API+2). 
Unfortunately the [UAPI](https://documentation.cPanel.net/display/DD/Guide+to+UAPI) that is recommended does not have support for creating addon domains.
The main idea behind is for staging purposes but I guess you can use it for other interesting conecpts.
The idea is, every branch possibly has its own staging domain/subdomain (staging-neat-feature.project.com) and database db_neat-feature_project so it can be tested.
This recipe can make the domain/subdomain and database creation part of the deployment process so you don't have to manually create them through an interface.
Since this is my first recipe, I welcome all the feedback and improvements that can be done
| Q …

cPanel functionality as deployer recipe

---

docs/directadmin.md
recipe/directadmin.php

This DirectAdmin recipe allows you to add and delete domains and databases on a DirectAdmin server. I use the DirectAdmin API to make this possible so there is no 3th party package required.
I use this for creating and removing domains for every branch so you have a 'review' environment.
If you have any feedback, let me know.

DirectAdmin recipe

---

recipe/slack.php

As the failure message has the red color I think that makes sense to have a green notification in a success case.

Slack > Success message green

---

CHANGELOG.md
recipe/sentry.php

The header is already set by called Httpie library. Calling ::header just adds a new header, does not do any replace: https://github.com/deployphp/deployer/blame/master/src/Utility/Httpie.php#L58-L67
Sentry does not recognize the request when we send the headers twice and fails with error:
```
[RuntimeException] on [factcool-www3.superhosting.cz]
Unable to create a release: Array
(
[detail] => Unsupported media type 'application/json, application/json' in request.
)
```
This merge requests fixed the issue.

Fix Sentry "Unsupported media type 'application/json, application/json' in request"

---

docs/npm.md
recipe/npm.php

As the documentation said (https://docs.npmjs.com/cli/ci.html) we should use npm ci install of npm install during deployments
> This command is similar to npm-install, except it’s meant to be used in automated environments such as test platforms, continuous integration, and deployment – or any situation where you want to make sure you’re doing a clean install of your dependencies. It can be significantly faster than a regular npm install by skipping certain user-oriented features. It is also more strict than a regular install, which can help catch errors or inconsistencies caused by the incrementally-installed local environments of most npm …

Add npm:ci (clean install) command to npm recipe

---

.gitignore
recipe/sentry.php

| Fixed tickets | #227 
I also added the lock file to the gitignore, as it's not included in packages.
> Do not forget to add notes about your changes to [CHANGELOG.md]
Do I add a new version to add to the change log?

fix: make sentry release work without git

---

CHANGELOG.md
docs/sentry.md
recipe/sentry.php

On Sentry.io releases are global per organization, so indipendent projects in same organization must use a prefix to version numbers to avoid conflicts (see https://docs.sentry.io/workflow/releases/?platform=php#configure-sdk)

Add optional version prefix to Sentry recipe

---

CHANGELOG.md
recipe/rabbit.php

The `'env'` configuration parameter is supposed to be an array of environment variables, but this recipe treats it like a string, so PHP throws an "Array to string conversion" notice and the message in the queue becomes muddy:
`Deployment to 'localhost' on *Array* was successful`
This patch instead makes use of the stage information (if available):
`Deployment to 'localhost' on *production* was successful`
`Deployment to 'localhost' was successful`

Fix a default message in the Rabbit recipe

---

docs/phinx.md

Some missing comma's cause an invalid array.

Fix $phinx_env_vars syntax

---

CHANGELOG.md
recipe/sentry.php

Ater fix, 
```
git rev-parse --git-dir > /dev/null 2>&1 && echo 1 || echo 0
```
return 0 if git does not exist, and return 1, if all good
Line git rev-parse --git-dir > /dev/null 2>&1 && echo 1 return code 128, if git does not exist
```
bash: 128: command not found
```
But symfony process return exception, if code it is not a zero
https://github.com/symfony/process/blob/7075b84559f3624c9f1fcde37c5af7a3e025ec8a/Process.php#L251

Fix Exit Code: 128 in sentry recipe

---

CHANGELOG.md
recipe/cachetool.php

After the release of the **5.X** family of cachetool, `cachetool.phar` no longer refers to a member of 4.X family, but to the last tag of the new family instead. This introduces an error when **cachetool** is executed from an environment with PHP 7.1.X, as the new `cachetool.phar` works with PHP >=7.2.
E.g.
```
$ php71 /var/www/[...]/cachetool.phar --version
PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Console\Output\stream_isatty() in phar:///var/www/[...]/cachetool.phar/vendor/symfony/console/Output/StreamOutput.php:117
Stack trace:
#0 phar:///var/www/[...]/cachetool.phar/vendor/symfony/console/Output/StreamOutput.php(52): Symfony\Component\Console\Output\StreamOutput->hasColorSupport()
#1 phar:///var/www/[...]/cachetool.phar/vendor/symfony/console/Outpu …
```

Cachetool fix for 4.X family and PHP version 7.1.X

---

recipe/rollbar.php

The Rollbar notify command should be publicly accessible, otherwise an error like `There are no commands defined in the "rollbar" namespace.` gets thrown.
| BC breaks?    |  No

Remove private mode from Rollbar recipe.
